apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-blog-deployment
spec:
  selector:
    matchLabels:
      app: nextjs-blog
  replicas: 1
  template:
    metadata:
      labels:
        app: nextjs-blog
    spec:
      containers:
      - name: nextjs-blog-container
        image: ityuhui/nextjs-blog:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000